In [32]:
import pandas as pd

data = pd.read_csv("./size.csv", header=None)
data

                  0         1
0    HiC_scaffold_1  54426268
1    HiC_scaffold_2  51175917
2    HiC_scaffold_3  51171312
3    HiC_scaffold_4  60021211
4    HiC_scaffold_5  56436372
5    HiC_scaffold_6  45356544
6    HiC_scaffold_7  51057549
7    HiC_scaffold_8  66795888
8    HiC_scaffold_9  57405994
9   HiC_scaffold_10  58276289
10  HiC_scaffold_11  62111302
11  HiC_scaffold_12  55520912

In [62]:
dist = []
import numpy as np
import math
import seaborn as sns

for v1 in list(data[1]):
    temp = []
    for v2 in list(data[1]):
        temp.append(int(math.sqrt((int(v1)-int(v2))**2)))
    dist.append(temp)

for i, l in enumerate(dist):
    l[i]=9999999999
    
for i, l in enumerate(dist):
    print(i+1, " -> ", np.argmin(l) + 1, " : ", min(l))

1  ->  12  :  1094644
2  ->  3  :  4605
3  ->  2  :  4605
4  ->  10  :  1744922
5  ->  12  :  915460
6  ->  7  :  5701005
7  ->  3  :  113763
8  ->  11  :  4684586
9  ->  10  :  870295
10  ->  9  :  870295
11  ->  4  :  2090091
12  ->  5  :  915460